### ISSUE TITLE
execution halted for some reason

### ISSUE THREAD

**Issue by mvheetve** [nghiavtr/FuSeq#16]
Hi Nghia

several of my samples generated this output:

Parameter settings:
 readStrands= UN
 chromRef=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y
 maxSharedCount= 0.05
 onlyProteinCodingGenes= FALSE
 minGeneDist= 10000
 minJunctionDist= 1e+05
 maxInvertedFusionCount= 0
 maxMRfusionFc= 2
 maxMRfusionNum= 2
 sgtMRcount= 10
 minMR= 2
 minNonDupMR= 2
 minSR= 1
 minScore= 3
 exonBoundary= FALSE
 keepRData= TRUE
 exportFasta= TRUE

 Processing mapped reads (MR) from dataset:  /data/gent/vo/000/gvo00082/research/mvheetve/FuSeq/feqdir/18B11873_S4_L001  read strands: UN
 Read fusion equivalence classes
 Reading  /data/gent/vo/000/gvo00082/research/mvheetve/FuSeq/feqdir/18B11873_S4_L001/feq_UN.txt
 The total number of fusion equivalence classes:  52
 Create the maps between feq and fge'select()' returned many:1 mapping between keys and columns

 Get the number of supporting reads
 Get the number of uniquely mapped supporting reads
 Correct the number of supporting reads
 Keep only candidates in the selected chromosomes
 Extract other biological information...'select()' returned 1:1 mapping between keys and columns

 Extract extra features...'select()' returned 1:many mapping between keys and columns

 The total number of fge candidates:  43
 Start filtering ...
 The number of remaining fge candidates:  13
 Get the sum count of ftx
 Continue the filtering ...
 The number of remaining fge candidates:  8
 Filter by biological features... 
 Eliminate the fusion between genes and their paralogs
 Eliminate the fusion between single gene and read-through gene
 The number of remaining fge candidates:  8
 Filter by sequence similarity... 
 The number of remaining fge candidates:  6
 Detect junction breaks... 
 Get mapped fusion readsError in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: processMappedRead -> detectJunctionBreaks -> read.csv -> read.table
In addition: There were 18 warnings (use warnings() to see them)
Execution halted

Any idea what causes it? If it helps you can find the feqdir for the example I just gave here: 
https://we.tl/t-bBSJyBocsb
I noticed there's a lot more files in the feqdir than usual. This is Illumina MiSeq 2x150bp data, trimmed and filtered using fastp (https://github.com/OpenGene/fastp#features).

Kind regards
Mattias

**Comment by nghiavtr** [comment]
Hi Mattias,

I have a quick look at your data. The error is due to one file UN_fusionMappedReadsChunk_1804289383.txt  have no data, so the function read.csv() of R which is called from detectJunctionBreaks() returns the error. This happens because your data sample is quite small but you run in too many threads (36 CPUs).

So I think a simple solution for this moment is that you reduce the number of threads in running FuSeq, maybe to 4 CPUs. Thus, we can avoid the zero-content file in the output of FuSeq.

This is a weird bug, thank you for report this to us. I will fix this in the next version of FuSeq.
Good luck with your research!

Best wishes,
Nghia

**Comment by mvheetve** [comment]
Hej, 

that completely fixed the problem! Stupid of me not to consider the number of cores. For some reason I didn't include the -p option this time. Two thoughts:
1) maybe add a default number of cores to FuSeq
2) Is there a possibility of adding an overview of all options (and their defaults) to the FuSeq homepage? If I'm not mistaken it only provides an overview of the parameter settings at this point.

Thanks again and all the best!
Mattias
