### ISSUE TITLE
Error with ex_createAnno.R script

### ISSUE THREAD

**Issue by Troyee13** [nghiavtr/FuSeq#20]
Hello,

When I am trying to build the Anno data with the following command
Rscript ex_createAnno.R hg38_clean_cDNA.fa hg38.txAnno.RData
I am getting an error
Error: unexpected '<' in "<"
Execution halted
Done!

Any suggestion on how to resolve this issue?

**Comment by nghiavtr** [comment]
Hi @Troyee13,

Thank you for using FuSeq.

I haven't got this issue before, can you let me know the exact hg38 annotation version you are using?

Best,
Nghia

**Comment by Troyee13** [comment]
Thanks for the reply. 

The error was because I didn't put excreate_Anno.R not within the R folder of FuSeq. Now it is running fine. I am using Ensembl version 104 annotation right now. I will be closing this issue.
