### ISSUE TITLE
installing fails under ubuntu 16.04.6 LTS

### ISSUE THREAD

**Issue by splaisan** [nghiavtr/FuSeq#4]
I cannot manage to build on my machine. Sailfish cannot be installed because the system boost is only 1.58.
I also had errors dues to the Intel block dependency although I installed libtbb-dev
The install.sh script fails at that stage and running from the latest build is also bad with error

`./FuSeq: relocation error: /opt/biotools/FuSeq_v1.1.1_linux_x86-64/linux/bin/../lib/librt.so.1: symbol __vdso_clock_gettime, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference`

Did someone manage to build FuSeq on ubuntu 16.04.6 LTS xenial?

**Comment by nghiavtr** [comment]
Hi @splaisan,

Thank you for your considering FuSeq in your research. Your issue is likely a common problem with Ubuntu, which is similar to the one here:  https://github.com/nghiavtr/FuSeq/issues/1

If so, the solution is simply removing "librt.so.1" from the lib folder.

Best,
Nghia

**Comment by splaisan** [comment]
This fixed it and it now runs the --help.
Thanks
