### ISSUE TITLE
Getting error when indexing

### ISSUE THREAD

**Issue by Dagsbio** [nghiavtr/FuSeq#5]
I always get this error when indexing the transcriptome (and I have tried with 2 different transcriptomes): 

---------------------------------------------------------------

--- FuSeq acknowledges the Sailfish and Rapmap for this indexer ---

---------------------------------------------------------------

writing log to TxIndexer_idx/LogDir/FuSeq_index.log
RapMap Indexer

[Step 1 of 4] : counting k-mers
counted k-mers for 180000 transcriptsElapsed time: 2.71158s

Replaced 5 non-ATCG nucleotides
Clipped poly-A tails from 1439 transcripts
Building rank-select dictionary and saving to disk done
Elapsed time: 0.0179622s
Writing sequence data to file . . . done
Elapsed time: 0.155172s
[info] Building 32-bit suffix array (length of generalized text is 316958305)
Building suffix array . . . success
saving to disk . . . done
Elapsed time: 1.592s
done
Elapsed time: 30.6721s
processed 195000000 positionsTxIndexer: /proj/uppstore2017200/b2012036/Nghia/Tools/TestFuSeqInstallation/FuSeq-1.1.0/sailfish-0.10.0/external/install/include/sparsehash/internal/densehashtable.h:782: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const long unsigned int, rapmap::utils::SAInterval<int> >; Key = long unsigned int; HashFcn = rapmap::utils::KmerKeyHasher; ExtractKey = google::dense_hash_map<long unsigned int, rapmap::utils::SAInterval<int>, rapmap::utils::KmerKeyHasher, std::equal_to<long unsigned int>, google::libc_allocator_with_realloc<std::pair<const long unsigned int, rapmap::utils::SAInterval<int> > > >::SelectKey; SetKey = google::dense_hash_map<long unsigned int, rapmap::utils::SAInterval<int>, rapmap::utils::KmerKeyHasher, std::equal_to<long unsigned int>, google::libc_allocator_with_realloc<std::pair<const long unsigned int, rapmap::utils::SAInterval<int> > > >::SetKey; EqualKey = std::equal_to<long unsigned int>; Alloc = google::libc_allocator_with_realloc<std::pair<const long unsigned int, rapmap::utils::SAInterval<int> > >; google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]: Assertion `table' failed.
Aborted (core dumped)

**Comment by Dagsbio** [comment]
By the way I only have 8GB of RAM, I guess that's the problem?

**Comment by nghiavtr** [comment]
Dear @Dagsbio,

Thank you for using FuSeq. 
This error of "core dumped" in the Indexer is quite rare, normally caused by the lack of memory, storage space due to a big fasta file.  So you are right, might be 8GB memory is too small for your fasta sequences. 

If you increase the memory to 16GB but still get the problem, can you tell me the OS you are using and also send me an example of fasta file you encountered the error, I will take a look if the problem comes from FuSeq.

Good lucks,
Nghia
