### ISSUE TITLE
error with some library

### ISSUE THREAD

**Issue by Dagsbio** [nghiavtr/FuSeq#8]
Hi, I have installed the new version and tried running FuSeq on Ubuntu 18.04 but I am getting this error and can't find a solution for it:
relocation error: /home/david/Software/FuSeq_v1.1.2_linux_x86-64/linux/bin/../lib/librt.so.1: symbol __vdso_clock_gettime version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

Any ideas?

Thank you

**Comment by nghiavtr** [comment]
Dear Dagsbio,

Thank you for using FuSeq.

This issue can be solved simply by **removing two files: librt.so.1 and libc.so.6** from folder FuSeq_v1.1.2_linux_x86-64/linux/lib, then it should work.

Best,
Nghia

**Comment by Dagsbio** [comment]
Thanks!, that worked. But now I am encountering an error when running FuSeq.R: 

"
Error in load(txAnnofile) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘gencode.v29lift37.annotation.gtf’ has magic number '##des'
  Use of save versions prior to 2 is deprecated 
Execution halted
"

Do you know whats happening?

Thank you.

**Comment by nghiavtr** [comment]
Hi,

The error is simply that it can not load the RData annotation file.

It is likely that you do not use the "Homo_sapiens.GRCh37.75.txAnno.RData" supplied by FuSeq's website for your analysis. Can you describe more details about how you get the RData annotation file (txAnno), is this from gencode.v29?

Nghia

**Comment by Dagsbio** [comment]
Hi, 

Yes, I am using "gencode.v29lift37.annotation.gtf" file. Although I realised I am running FuSeq.R directly using an absolute path like:  ~/Software/FuSeq_v1.1.2_linux_x86-64/R/FuSeq.R so might be that the problem?

Thanks

**Comment by Dagsbio** [comment]
The command was exactly this: 
Rscript ~/Software/FuSeq_v1.1.2_linux_x86-64/R/FuSeq.R in=FuSeq_output txfasta=gencode.v29lift37.pc_transcripts.fa  sqlite=gencode.v29lift37.annotation.sqlite txanno=gencode.v29lift37.annotation.gtf out=test

**Comment by Dagsbio** [comment]
Sorry was totally my fault, just rechecked the command which obviously was wrong! It works now. 

Thanks.
